version: "3"

tasks:
  generate-cognito:
    vars:
      COGNITO_USER_POOL_ID:
        sh: aws cognito-idp list-user-pools --max-results 10 --query 'UserPools[?starts_with(Name, `slchess-dev`)].Id' --output text
      COGNITO_USER_POOL_CLIENT_ID:
        sh: aws cognito-idp list-user-pool-clients --user-pool-id {{.COGNITO_USER_POOL_ID}} --query 'UserPoolClients[?starts_with(ClientName, `slchess-dev`)].ClientId' --output text
    cmds:
      - echo "COGNITO_URL=slchess-dev.auth.ap-southeast-2.amazoncognito.com" > ./lib/.env
      - echo "COGNITO_CLIENT_ID={{.COGNITO_USER_POOL_CLIENT_ID}}" >> ./lib/.env
